name = "ebpf_verifier_range_analysis"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["EbpfVerifierRangeAnalysis"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "EbpfVerifierRangeAnalysis"
